DOTS = {
    3442: {
        "buff_name": "流血(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 2,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            52,
            54,
            56,
            58,
            60
        ],
        "physical_damage_call": 1
    },
    12461: {
        "buff_name": "流血(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 3,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            52,
            54,
            56,
            58,
            60
        ],
        "physical_damage_call": 1
    },
    2920: {
        "buff_name": "急曲(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": [
            15,
            18,
            20,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            44,
            48,
            52,
            56,
            60,
            64,
            68,
            72,
            76,
            80,
            84,
            88,
            92,
            96,
            100
        ],
        "lunar_damage_call": 1
    },
    70030: {
        "buff_name": "急曲·悟(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 1,
        "damage_base": 15,
        "lunar_damage_call": 1
    },
    6218: {
        "buff_name": "蝎心(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            10,
            12,
            14,
            16,
            18,
            20,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            53,
            56,
            59,
            62,
            65,
            68,
            71,
            74,
            77,
            80
        ],
        "poison_damage_call": 1
    },
    2509: {
        "buff_name": "百足(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            14,
            15,
            16,
            17,
            18,
            19,
            21,
            24,
            27,
            29,
            32,
            34,
            37,
            40,
            42,
            45,
            47,
            50,
            53,
            55,
            58,
            60,
            63,
            66,
            68,
            71,
            73,
            76,
            79,
            81,
            84,
            86,
            89,
            92
        ],
        "poison_damage_call": 1
    },
    12557: {
        "buff_name": "百足(DOT)",
        "interval": 32,
        "tick": 9,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            14,
            15,
            16,
            17,
            18,
            19,
            21,
            24,
            27,
            29,
            32,
            34,
            37,
            40,
            42,
            45,
            47,
            50,
            53,
            55,
            58,
            60,
            63,
            66,
            68,
            71,
            73,
            76,
            79,
            81,
            84,
            86,
            89,
            92
        ],
        "poison_damage_call": 1
    },
    2295: {
        "buff_name": "蟾啸(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50
        ],
        "poison_damage_call": 1
    },
    18882: {
        "buff_name": "赤蛇(DOT)",
        "interval": 48,
        "tick": 10,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 20,
        "poison_damage_call": 1
    },
    2296: {
        "buff_name": "蛇影(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            31,
            33,
            35,
            37,
            39,
            41,
            43,
            45,
            47,
            49,
            51,
            53,
            55
        ],
        "poison_damage_call": 1
    },
    25917: {
        "buff_name": "蛇影(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 2,
        "platform": 0,
        "damage_base": 55,
        "poison_damage_call": 1
    },
    11447: {
        "buff_name": "闹须弥(DOT)",
        "interval": 48,
        "tick": 8,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            25,
            28,
            31,
            34,
            37,
            40,
            43,
            46,
            49,
            52
        ],
        "physical_damage_call": 1
    },
    19555: {
        "buff_name": "背水沉舟(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 25,
        "physical_damage_call": 1
    },
    70364: {
        "buff_name": "流血(DOT)",
        "interval": [
            32,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48,
            48
        ],
        "tick": 8,
        "max_stack": 1,
        "platform": 1,
        "damage_base": [
            25,
            28,
            31,
            34,
            37,
            40,
            43,
            46,
            49,
            52
        ],
        "physical_damage_call": 1
    }
}
