DOTS = {
    743: {
        "skill_name": "横扫六合(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3
        ],
        "platform": 0,
        "damage_base": [
            12,
            13,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            32,
            33,
            34,
            35,
            37,
            38,
            39,
            41,
            42,
            43,
            45,
            12,
            13,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            32,
            33,
            34,
            35,
            37,
            38,
            39,
            41,
            42,
            43,
            45
        ],
        "magical_damage_call": 1
    },
    6424: {
        "skill_name": "气竭(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 50,
        "magical_damage_call": 1
    },
    748: {
        "skill_name": "叠刃(DOT)",
        "interval": 48,
        "tick": 8,
        "max_stack": [
            5,
            7
        ],
        "platform": 0,
        "damage_base": 10,
        "physical_damage_call": 1
    },
    889: {
        "skill_name": "人剑合一(DOT)",
        "interval": 48,
        "tick": 4,
        "max_stack": 1,
        "platform": 0,
        "damage_base": 16,
        "physical_damage_call": 1
    },
    23170: {
        "skill_name": "万象归元(DOT)",
        "interval": 48,
        "tick": 10,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 10,
        "physical_damage_call": 1
    },
    711: {
        "skill_name": "兰摧玉折(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30
        ],
        "magical_damage_call": 1
    },
    714: {
        "skill_name": "钟林毓秀(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            34,
            36,
            38
        ],
        "magical_damage_call": 1
    },
    666: {
        "skill_name": "商阳指(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            33,
            35,
            37,
            39,
            41,
            43,
            45,
            46,
            48,
            50
        ],
        "magical_damage_call": 1
    },
    24158: {
        "skill_name": "快雪时晴(DOT)",
        "interval": 64,
        "tick": 7,
        "max_stack": 6,
        "platform": 0,
        "damage_base": 38,
        "magical_damage_call": 1
    },
    3442: {
        "skill_name": "流血(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 2,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            52,
            54,
            56,
            58,
            60
        ],
        "physical_damage_call": 1
    },
    12461: {
        "skill_name": "流血(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 3,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            52,
            54,
            56,
            58,
            60
        ],
        "physical_damage_call": 1
    },
    2920: {
        "skill_name": "急曲(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": [
            15,
            18,
            20,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            44,
            48,
            52,
            56,
            60,
            64,
            68,
            72,
            76,
            80,
            84,
            88,
            92,
            96,
            100
        ],
        "magical_damage_call": 1
    },
    6218: {
        "skill_name": "蝎心(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            10,
            12,
            14,
            16,
            18,
            20,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            53,
            56,
            59,
            62,
            65,
            68,
            71,
            74,
            77,
            80
        ],
        "magical_damage_call": 1
    },
    2509: {
        "skill_name": "百足(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            14,
            15,
            16,
            17,
            18,
            19,
            21,
            24,
            27,
            29,
            32,
            34,
            37,
            40,
            42,
            45,
            47,
            50,
            53,
            55,
            58,
            60,
            63,
            66,
            68,
            71,
            73,
            76,
            79,
            81,
            84,
            86,
            89,
            92
        ],
        "magical_damage_call": 1
    },
    2295: {
        "skill_name": "蟾啸(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50
        ],
        "magical_damage_call": 1
    },
    18882: {
        "skill_name": "赤蛇(DOT)",
        "interval": 48,
        "tick": 10,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 20,
        "magical_damage_call": 1
    },
    25917: {
        "skill_name": "蛇影(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 2,
        "platform": 0,
        "damage_base": 55,
        "magical_damage_call": 1
    },
    2237: {
        "skill_name": "穿心(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 2,
        "platform": 0,
        "damage_base": [
            19,
            21,
            23,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            49,
            52,
            55,
            58,
            61,
            64,
            67,
            70,
            75,
            80,
            85,
            90,
            95,
            100
        ],
        "physical_damage_call": 1
    },
    19625: {
        "skill_name": "星斗阑干(DOT)",
        "interval": 48,
        "tick": 10,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 25,
        "physical_damage_call": 1
    },
    14611: {
        "skill_name": "化血(DOT)",
        "interval": 48,
        "tick": 16,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            19,
            21,
            23,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            41,
            42,
            43,
            46,
            49,
            52,
            55,
            58,
            61,
            64,
            67,
            70,
            75,
            80,
            85,
            90,
            95,
            100
        ],
        "magical_damage_call": 1
    },
    4202: {
        "skill_name": "银月斩(DOT)",
        "interval": 32,
        "tick": 9,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            12,
            14,
            16,
            18,
            20,
            22,
            24,
            27,
            30,
            33,
            36,
            39,
            42,
            45,
            48,
            51,
            53,
            55
        ],
        "magical_damage_call": 1
    },
    25725: {
        "skill_name": "靡业报劫·日(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 1,
        "platform": 0,
        "damage_base": 30,
        "magical_damage_call": 1
    },
    25726: {
        "skill_name": "靡业报劫·月(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 1,
        "platform": 0,
        "damage_base": 30,
        "magical_damage_call": 1
    },
    6401: {
        "skill_name": "亢龙有悔(DOT)",
        "interval": 48,
        "tick": 10,
        "max_stack": 10,
        "platform": 0,
        "damage_base": [
            5,
            6,
            7,
            8,
            9,
            10,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            22,
            24,
            26,
            28,
            30,
            33
        ],
        "physical_damage_call": 1
    },
    8249: {
        "skill_name": "流血(DOT)",
        "interval": [
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16
        ],
        "tick": [
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26
        ],
        "max_stack": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            3,
            3,
            3,
            3,
            3,
            3,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
        ],
        "platform": 0,
        "damage_base": [
            5,
            7,
            9,
            11,
            13,
            15,
            17,
            19,
            21,
            23,
            25,
            27,
            29,
            31,
            33,
            35,
            37,
            39,
            41,
            43,
            45,
            47,
            49,
            51,
            53,
            55,
            57,
            60,
            5,
            7,
            9,
            11,
            13,
            15,
            17,
            19,
            21,
            23,
            25,
            27,
            29,
            31,
            33,
            35,
            37,
            39,
            41,
            43,
            45,
            47,
            49,
            51,
            53,
            55,
            57,
            60
        ],
        "physical_damage_call": 1
    },
    9357: {
        "skill_name": "商(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            12,
            14,
            16,
            18,
            20,
            21,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            52,
            54,
            56,
            58
        ],
        "magical_damage_call": 1
    },
    9361: {
        "skill_name": "角(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            12,
            14,
            16,
            18,
            19,
            20,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            52,
            54,
            56,
            58
        ],
        "magical_damage_call": 1
    },
    23187: {
        "skill_name": "神兵·宫(DOT)",
        "interval": 48,
        "tick": 10,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 58,
        "magical_damage_call": 1
    },
    11447: {
        "skill_name": "闹须弥(DOT)",
        "interval": 48,
        "tick": 8,
        "max_stack": 1,
        "platform": 0,
        "damage_base": [
            25,
            28,
            31,
            34,
            37,
            40,
            43,
            46,
            49,
            52
        ],
        "physical_damage_call": 1
    },
    19555: {
        "skill_name": "背水沉舟(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 25,
        "physical_damage_call": 1
    },
    18386: {
        "skill_name": "青冥(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 6,
        "platform": 0,
        "damage_base": 50,
        "physical_damage_call": 1
    },
    19557: {
        "skill_name": "御波驾澜(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 25,
        "physical_damage_call": 1
    },
    15568: {
        "skill_name": "寂洪荒(DOT)",
        "interval": 48,
        "tick": 5,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 25,
        "physical_damage_call": 1
    },
    19626: {
        "skill_name": "乍起狂澜(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 25,
        "physical_damage_call": 1
    },
    24846: {
        "skill_name": "斗循天转(DOT)",
        "interval": 48,
        "tick": 10,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 15,
        "magical_damage_call": 1
    },
    20052: {
        "skill_name": "逆乱(DOT)",
        "interval": 32,
        "tick": 7,
        "max_stack": 8,
        "platform": 0,
        "damage_base": [
            10,
            12,
            15,
            21,
            28,
            35,
            46,
            62,
            74,
            95
        ],
        "magical_damage_call": 1
    },
    71171: {
        "skill_name": "中毒(DOT)",
        "interval": 16,
        "tick": 6,
        "max_stack": 1,
        "platform": 1,
        "damage_base": 1,
        "magical_damage_call": 1
    },
    24132: {
        "skill_name": "流血(DOT)",
        "interval": 32,
        "tick": 3,
        "max_stack": 4,
        "platform": 0,
        "damage_base": [
            12,
            18,
            24,
            30,
            36,
            42,
            48,
            54,
            60,
            66,
            72,
            78,
            84,
            90,
            96,
            102,
            108
        ],
        "physical_damage_call": 1
    },
    24443: {
        "skill_name": "流血(DOT)",
        "interval": 32,
        "tick": 3,
        "max_stack": 6,
        "platform": 0,
        "damage_base": [
            12,
            18,
            24,
            30,
            36,
            42,
            48,
            54,
            60,
            72,
            78,
            84,
            90,
            96,
            102,
            108,
            114
        ],
        "physical_damage_call": 1
    },
    24650: {
        "skill_name": "截辕(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 1,
        "platform": 0,
        "damage_base": 102,
        "physical_damage_call": 1
    },
    27820: {
        "skill_name": "斩浪破锋(DOT)",
        "interval": 48,
        "tick": 6,
        "max_stack": 3,
        "platform": 0,
        "damage_base": 25,
        "physical_damage_call": 1
    },
    70583: {
        "skill_name": "流血(DOT)",
        "interval": 32,
        "tick": 9,
        "max_stack": [
            1,
            3
        ],
        "platform": 1,
        "damage_base": 12,
        "physical_damage_call": 1
    },
    70593: {
        "skill_name": "截辕·悟(DOT)",
        "interval": 32,
        "tick": 6,
        "max_stack": 1,
        "platform": 1,
        "damage_base": 102,
        "physical_damage_call": 1
    },
    26856: {
        "skill_name": "贯穿(DOT)",
        "interval": 8,
        "tick": 4,
        "max_stack": 6,
        "platform": 0,
        "damage_base": 32,
        "physical_damage_call": 1
    },
    71175: {
        "skill_name": "流血(DOT)",
        "interval": 16,
        "tick": 6,
        "max_stack": 1,
        "platform": 1,
        "damage_base": 10,
        "physical_damage_call": 1
    }
}