DOTS = {
    "743": {
        "skill_name": "横扫六合(DOT)",
        "interval": 32,
        "origin_tick": 6,
        "max_stack": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3
        ]
    },
    "6424": {
        "skill_name": "气竭(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 3
    },
    "748": {
        "skill_name": "叠刃(DOT)",
        "interval": 48,
        "origin_tick": 8,
        "max_stack": [
            5,
            7
        ]
    },
    "889": {
        "skill_name": "人剑合一(DOT)",
        "interval": 48,
        "origin_tick": 4,
        "max_stack": 1
    },
    "23170": {
        "skill_name": "万象归元(DOT)",
        "interval": 48,
        "origin_tick": 10,
        "max_stack": 3
    },
    "711": {
        "skill_name": "兰摧玉折(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 1
    },
    "714": {
        "skill_name": "钟林毓秀(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 1
    },
    "666": {
        "skill_name": "商阳指(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 1
    },
    "24158": {
        "skill_name": "快雪时晴(DOT)",
        "interval": 64,
        "origin_tick": 7,
        "max_stack": 6
    },
    "3442": {
        "skill_name": "流血(DOT)",
        "interval": 32,
        "origin_tick": 7,
        "max_stack": 2
    },
    "2920": {
        "skill_name": "急曲(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 3
    },
    "6218": {
        "skill_name": "蝎心(DOT)",
        "interval": 32,
        "origin_tick": 6,
        "max_stack": 1
    },
    "2509": {
        "skill_name": "百足(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 1
    },
    "2295": {
        "skill_name": "蟾啸(DOT)",
        "interval": 32,
        "origin_tick": 7,
        "max_stack": 1
    },
    "18882": {
        "skill_name": "赤蛇(DOT)",
        "interval": 48,
        "origin_tick": 10,
        "max_stack": 3
    },
    "25917": {
        "skill_name": "蛇影(DOT)",
        "interval": 32,
        "origin_tick": 6,
        "max_stack": 2
    },
    "2237": {
        "skill_name": "穿心(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 2
    },
    "19625": {
        "skill_name": "星斗阑干(DOT)",
        "interval": 48,
        "origin_tick": 10,
        "max_stack": 3
    },
    "14611": {
        "skill_name": "化血(DOT)",
        "interval": 48,
        "origin_tick": 16,
        "max_stack": 1
    },
    "4202": {
        "skill_name": "银月斩(DOT)",
        "interval": 32,
        "origin_tick": 9,
        "max_stack": 1
    },
    "25725": {
        "skill_name": "靡业报劫·日(DOT)",
        "interval": 32,
        "origin_tick": 7,
        "max_stack": 1
    },
    "25726": {
        "skill_name": "靡业报劫·月(DOT)",
        "interval": 32,
        "origin_tick": 7,
        "max_stack": 1
    },
    "6401": {
        "skill_name": "亢龙有悔(DOT)",
        "interval": 48,
        "origin_tick": 10,
        "max_stack": 10
    },
    "8249": {
        "skill_name": "流血(DOT)",
        "interval": [
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            32,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16
        ],
        "origin_tick": [
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26,
            26
        ],
        "max_stack": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            3,
            3,
            3,
            3,
            3,
            3,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
        ]
    },
    "9357": {
        "skill_name": "商(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 1
    },
    "9361": {
        "skill_name": "角(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 1
    },
    "23187": {
        "skill_name": "神兵·宫(DOT)",
        "interval": 48,
        "origin_tick": 10,
        "max_stack": 3
    },
    "11447": {
        "skill_name": "闹须弥(DOT)",
        "interval": 48,
        "origin_tick": 8,
        "max_stack": 1
    },
    "19555": {
        "skill_name": "背水沉舟(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 3
    },
    "18386": {
        "skill_name": "青冥(DOT)",
        "interval": 32,
        "origin_tick": 6,
        "max_stack": 6
    },
    "19557": {
        "skill_name": "御波驾澜(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 3
    },
    "15568": {
        "skill_name": "寂洪荒(DOT)",
        "interval": 48,
        "origin_tick": 5,
        "max_stack": 3
    },
    "19626": {
        "skill_name": "乍起狂澜(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 3
    },
    "24846": {
        "skill_name": "斗循天转(DOT)",
        "interval": 48,
        "origin_tick": 10,
        "max_stack": 3
    },
    "20052": {
        "skill_name": "逆乱(DOT)",
        "interval": 32,
        "origin_tick": 7,
        "max_stack": 8
    },
    "24443": {
        "skill_name": "流血(DOT)",
        "interval": 32,
        "origin_tick": 3,
        "max_stack": 6
    },
    "27820": {
        "skill_name": "斩浪破锋(DOT)",
        "interval": 48,
        "origin_tick": 6,
        "max_stack": 3
    },
    "26856": {
        "skill_name": "贯穿(DOT)",
        "interval": 8,
        "origin_tick": 4,
        "max_stack": 6
    }
}