name: Sync to Space
on:
  push:
    branches: [ "gradio" ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push -f https://AngoHF:$HF_TOKEN@huggingface.co/spaces/AngoHF/Formulator gradio:main
#      - name: Push to ModelScope
#        env:
#          MS_TOKEN: ${{ secrets.MS_TOKEN }}
#        run: git push -f http://oauth2:$MS_TOKEN@www.modelscope.cn/studios/AngoMS/Formulator.git gradio:master
